# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: release

on:
  release:
    types: [created]

jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
    - name: checkout repository
      uses: actions/checkout@v2
    - name: validate gradle wrapper
      uses: gradle/wrapper-validation-action@v1
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: make gradle wrapper executable
      run: chmod +x ./gradlew
      
    - name: build
      run: ./gradlew build
      env:
        BUILD_RELEASE: ${{ github.event.prerelease == false }}
    
    - name: Upload assets to a Release
      uses: AButler/upload-release-assets@v2.0
      with:
        files: 'build/libs/*'
        # secrets.GITHUB_TOKEN
        repo-token: ${{ secrets.GITHUB_TOKEN }}
